import React from 'react'
import { render } from 'react-dom'
import App from './modules/App'
import NavBar from './modules/navbar'
import Footer from './modules/footer'
import Middle from './modules/middle'
